# .github/workflows/mirror-to-public.yml
name: Mirror to Public Repository

on:
  push:
    branches: [ version/2.3 ]
  workflow_dispatch:

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.PRIVATE_REPO_TOKEN }}

      - name: Prepare repository for public mirror
        run: |
          # Remove sensitive files and directories
          rm -rf .github/workflows/mirror-to-public.yml
          rm -rf .github/workflows/*private* 2>/dev/null || true
          rm -f .env* 2>/dev/null || true
          rm -rf secrets/ 2>/dev/null || true
          rm -f *.key *.pem 2>/dev/null || true
          
          EOF

      - name: Setup SSH for deployment
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.PUBLIC_REPO_DEPLOY_KEY }}" > ~/.ssh/deploy_key
          chmod 600 ~/.ssh/deploy_key
          ssh-keyscan github.com >> ~/.ssh/known_hosts

      - name: Mirror to public repository
        run: |
          # Configure git
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          
          # Add public repo as remote
          git remote add public git@github.com:ramin-fazli/quant-trading-system.git
          
          # Configure SSH to use deploy key
          export GIT_SSH_COMMAND="ssh -i ~/.ssh/deploy_key -o StrictHostKeyChecking=no"
          
          # Push to public repository
          git add .
          git commit -m "Mirror from private repository - $(date '+%Y-%m-%d %H:%M:%S')" || echo "No changes to commit"
          git push public HEAD:main --force